baseURL = 'https://footnote.wiki'
languageCode = 'en-us'
title = 'Footnote - Local-first wiki for friends and family'

[params]
  description = 'A local-first, zero-cloud, peer sync wiki for friends and family'
  personal_site = 'https://www.natehardt.dev'
  github_url = 'https://github.com/nhardt/footnote' 
